### ISSUE TITLE
Homebridge crashing after a few hours

### ISSUE THREAD

**Issue by noaboa97** [KraigM/homebridge-harmonyhub#100]
Hello,

So I got my homebridge working but after a few hours it'll crash and I get this error. 
In the Homebridge forum pdlove said it looks like hamronyhub plugin is causing this.

errorhub { Error: connect ETIMEDOUT 192.168.1.139:5222
at Object.exports._errnoException (util.js:1018:11)
at exports._exceptionWithHostPort (util.js:1041:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
code: 'ETIMEDOUT',
errno: 'ETIMEDOUT',
syscall: 'connect',
address: '192.168.1.139',
port: 5222 }
errorhub { Error: connect EHOSTUNREACH 192.168.1.139:5222
at Object.exports._errnoException (util.js:1018:11)
at exports._exceptionWithHostPort (util.js:1041:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
code: 'EHOSTUNREACH',
errno: 'EHOSTUNREACH',
syscall: 'connect',
address: '192.168.1.139',
port: 5222 }
events.js:160
throw er; // Unhandled 'error' event
^

Error: MAX_CLIENTS=6
at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:355:17)
at StreamParser. (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:226:10)
at emitOne (events.js:96:13)
at StreamParser.emit (events.js:188:7)
at SaxLtx. (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
at emitOne (events.js:96:13)
at SaxLtx.emit (events.js:188:7)
at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/ltx/lib/parsers/ltx.js:31:18)
at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/ltx/lib/parsers/ltx.js:105:26)
at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:305:17)
at emitOne (events.js:101:20)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:547:20)
root@raspberrypi:# OS

does anybody have an idea whats wrong?

thanks in advance

**Comment by ToddGreenfield** [comment]
Check out issue #80-

**Comment by noaboa97** [comment]
@ToddGreenfield and how is this issue related to mine? It does not happen when I'm off network it always crashes after a few hours it doesn't matter if I'm at home or at work.

**Comment by ToddGreenfield** [comment]
@noaboa97 apologies, I meant to type issue #84 as mentioned in the main homebridge thread that you also questioned. 

They are the same issue and error, which is the max clients error many experience.

**Comment by noaboa97** [comment]
I read a lot of stuff so I thought I just make sure it's not the connection of the harmony to my router wich fails or somethings with the network. So I placed another router next to my hamrony hub and since then my homebridge hasn't crashed. Although my router is in the living room and I've got my harmonyhub in my room wich is about 3-4 meters away with a wall between and I thought the connection is good but it turned out not to be...
