### ISSUE TITLE
Permission Denied Error when trying to re-install plugin

### ISSUE THREAD

**Issue by JGunner1970** [KraigM/homebridge-harmonyhub#112]
Having uninstalled everything and re-installed Homebrige itself, I am now unable to re-install HarmonyHub plugin due to a Permission Denied error.    Here is the contents of the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-harmonyhub',
1 verbose cli   '--unsafe-perm' ]
2 info using npm@5.5.1
3 info using node@v6.11.4
4 verbose npm-session e1ec20c58471d056
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-harmonyhub 483ms (from cache)
8 silly pacote tag manifest for homebridge-harmonyhub@latest fetched in 503ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-harmonyhub@0.3.0-alpha.2 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/debug 34ms (from cache)
15 http fetch GET 200 https://registry.npmjs.org/inherits 29ms (from cache)
16 http fetch GET 200 https://registry.npmjs.org/bluebird 37ms (from cache)
17 silly pacote range manifest for debug@^2.2.0 fetched in 42ms
18 silly resolveWithNewModule debug@2.6.9 checking installable status
19 silly pacote range manifest for inherits@^2.0.1 fetched in 38ms
20 silly resolveWithNewModule inherits@2.0.3 checking installable status
21 silly pacote range manifest for bluebird@^3.3.4 fetched in 45ms
22 silly resolveWithNewModule bluebird@3.5.1 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/harmonyhubjs-discover 65ms (from cache)
24 silly pacote range manifest for harmonyhubjs-discover@^1.0.2 fetched in 65ms
25 silly resolveWithNewModule harmonyhubjs-discover@1.0.3 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/lodash 115ms (from cache)
27 silly pacote range manifest for lodash@^4.6 fetched in 124ms
28 silly resolveWithNewModule lodash@4.17.4 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/queue 130ms (from cache)
30 silly pacote range manifest for queue@^3.1.0 fetched in 132ms
31 silly resolveWithNewModule queue@3.1.0 checking installable status
32 silly fetchPackageMetaData error for harmonyhubjs-client@github:e7hz3r0/harmonyhubjs-client Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/e7hz3r0/harmonyhubjs-client.git /Users/Jonathan/.npm/_cacache/tmp/git-clone-109c9395
32 silly fetchPackageMetaData /Users/Jonathan/.npm/_cacache/tmp/git-clone-109c9395/.git: Permission denied
33 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/e7hz3r0/harmonyhubjs-client.git /Users/Jonathan/.npm/_cacache/tmp/git-clone-109c9395
33 verbose stack /Users/Jonathan/.npm/_cacache/tmp/git-clone-109c9395/.git: Permission denied
33 verbose stack
33 verbose stack     at ChildProcess.exithandler (child_process.js:198:12)
33 verbose stack     at emitTwo (events.js:106:13)
33 verbose stack     at ChildProcess.emit (events.js:191:7)
33 verbose stack     at maybeClose (internal/child_process.js:920:16)
33 verbose stack     at Socket.<anonymous> (internal/child_process.js:351:11)
33 verbose stack     at emitOne (events.js:96:13)
33 verbose stack     at Socket.emit (events.js:188:7)
33 verbose stack     at Pipe._handle.close [as _onclose] (net.js:497:12)
34 verbose cwd /Users/Jonathan
35 verbose Darwin 17.2.0
36 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-harmonyhub" "--unsafe-perm"
37 verbose node v6.11.4
38 verbose npm  v5.5.1
39 error code 1
40 error Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/e7hz3r0/harmonyhubjs-client.git /Users/Jonathan/.npm/_cacache/tmp/git-clone-109c9395
40 error /Users/Jonathan/.npm/_cacache/tmp/git-clone-109c9395/.git: Permission denied
41 verbose exit [ 1, true ]
`

**Comment by Makk1000** [comment]
Downgrade npm to version 4. 
npm install -g npm@4

Install homebridge harmony-hub

Then update your npm version back to 5

That should do the trick

**Comment by JGunner1970** [comment]
Thank you @Makk1000 that has now worked!

**Comment by arnotron** [comment]
I ran into the same issue and this tip seems to have helped. However, after doing some research, it sounds to me like using a ssh://git@github.com URL, where a https://github.com URL should be.
Maybe the developers can have a look at this?
