### ISSUE TITLE
2 hubs and 1 make problem

### ISSUE THREAD

**Issue by m4d-maNu** [KraigM/homebridge-harmonyhub#116]
Hi,
i have 2 Harmonyhubs and 1 makes problems in the homebridge.

```
errorhub { Error: connect ETIMEDOUT 192.168.1.34:5222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.34',
  port: 5222 }
```

**Comment by m4d-maNu** [comment]
I could solve the problem.

1. Unistall the harmonyhub Plugin
2. Delete the cache file from the accessory ( ~/.homebridge/accessories/ )
3. Reinstall the harmonyhub Plugin
4. finish and his works now
