### ISSUE TITLE
Homebridge Keeps crashing

### ISSUE THREAD

**Issue by sdorilas** [KraigM/homebridge-harmonyhub#122]
And I believe it is because of Harmonyhub. I receive the following error:
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (XMPP authentication failure)
    at Client.emit (events.js:163:17)
    at Client._handleAuthState (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:298:10)
    at Client._handleStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:234:12)
    at Client.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:369:10)
    at StreamParser.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:28:22)
    at SaxLtx.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

**Comment by dMopp** [comment]
same

**Comment by sdorilas** [comment]
Hey @dMopp, did you ever resolve this or gave up like me?

**Comment by dMopp** [comment]
Somehow i solved it. But i cant tell you how, i was in ragemode :D

**Comment by sdorilas** [comment]
Lol lucky you!! Sounds good, enjoy!

**Comment by dMopp** [comment]
> 
> 
> Lol lucky you!! Sounds good, enjoy!

Hey, at leat, after some struggle, i get this plugin reinstalled....

(sudo npm install -g homebridge-harmonyhub - AS ROOT!!)

If i struggle again, i will net u know :)
