### ISSUE TITLE
install harmony hub problem

### ISSUE THREAD

**Issue by leflench** [KraigM/homebridge-harmonyhub#133]
hi im totally new to homebridge an all that stuff homebridge is install succesfully but im not able to install logitech harmony hub plugin i got that error message can someone help me out

thanks

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-harmonyhub' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 6ef107e4311f491c
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-harmonyhub 156ms (from cache)
8 silly pacote tag manifest for homebridge-harmonyhub@latest fetched in 234ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-harmonyhub@0.3.0-alpha.2 checking installable status
14 silly fetchPackageMetaData error for harmonyhubjs-client@github:e7hz3r0/harmonyhubjs-client No git binary found in $PATH
15 http fetch GET 304 https://registry.npmjs.org/debug 172ms (from cache)
16 silly pacote range manifest for debug@^2.2.0 fetched in 172ms
17 silly resolveWithNewModule debug@2.6.9 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/bluebird 219ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/queue 171ms (from cache)
20 silly pacote range manifest for bluebird@^3.3.4 fetched in 234ms
21 silly resolveWithNewModule bluebird@3.5.1 checking installable status
22 silly pacote range manifest for queue@^3.1.0 fetched in 171ms
23 silly resolveWithNewModule queue@3.1.0 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/lodash 171ms (from cache)
25 silly pacote range manifest for lodash@^4.6 fetched in 187ms
26 silly resolveWithNewModule lodash@4.17.5 checking installable status
27 http fetch GET 304 https://registry.npmjs.org/harmonyhubjs-discover 187ms (from cache)
28 silly pacote range manifest for harmonyhubjs-discover@^1.0.2 fetched in 187ms
29 silly resolveWithNewModule harmonyhubjs-discover@1.1.1 checking installable status
30 http fetch GET 304 https://registry.npmjs.org/inherits 187ms (from cache)
31 silly pacote range manifest for inherits@^2.0.1 fetched in 203ms
32 silly resolveWithNewModule inherits@2.0.3 checking installable status
33 verbose stack Error: No git binary found in $PATH
33 verbose stack     at checkGit (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:203:17)
33 verbose stack     at spawnGit (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:182:10)
33 verbose stack     at pinflight (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:114:12)
33 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
33 verbose stack     at Promise._execute (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:303:9)
33 verbose stack     at Promise._resolveFromExecutor (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:483:18)
33 verbose stack     at new Promise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
33 verbose stack     at _inflight (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
33 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
33 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
33 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
33 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
33 verbose stack     at Promise._settlePromiseCtx (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:606:10)
33 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
33 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
33 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
34 verbose cwd C:\Users\USER
35 verbose Windows_NT 6.1.7601
36 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge-harmonyhub"
37 verbose node v8.9.4
38 verbose npm  v5.6.0
39 error code ENOGIT
40 error No git binary found in $PATH
41 error Failed using git.
41 error Please check if you have git installed and in your PATH.
42 verbose exit [ 1, true ]

**Comment by DJay-X** [comment]
`sudo chown -R $USER /usr/local && npm install homebridge-harmonyhub -g`

Worked for me.
