### ISSUE TITLE
Installation plugin

### ISSUE THREAD

**Issue by gold2605** [KraigM/homebridge-harmonyhub#134]
Hello, I get the following error when installing the plugin. My Homebridge runs under the user homebridge and in unsafe mode. However, several installed plugins work correctly (Tado, Netatmo, homematic, config-ui-x, alexa, unifi). Why does not that work with harmony?

Error:

USER: homebridge
DIR: /usr/local/lib/node_modules
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-harmonyhub@latest

npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /home/homebridge/.npm/_cacache/tmp/git-clone-257a97d3
npm ERR! /home/homebridge/.npm/_cacache/tmp/git-clone-257a97d3/.git: Keine Berechtigung
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2018-05-11T14_43_07_720Z-debug.log

Command failed. Please review log for details

Log-Datei:

pi@raspberrypi:~ $ cat /home/homebridge/.npm/_logs/2018-05-11T14_43_07_720Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--no-update-notifier',
1 verbose cli   'install',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'homebridge-harmonyhub@latest' ]
2 info using npm@6.0.1
3 info using node@v8.8.1
4 verbose npm-session cd5c6a653dd3d870
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-harmonyhub 425ms
8 silly pacote tag manifest for homebridge-harmonyhub@latest fetched in 559ms
9 timing stage:loadCurrentTree Completed in 1451ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-harmonyhub@0.3.0-alpha.2 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/harmonyhubjs-discover 210ms
18 silly pacote range manifest for harmonyhubjs-discover@^1.0.2 fetched in 367ms
19 silly resolveWithNewModule harmonyhubjs-discover@1.1.1 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/queue 370ms
21 http fetch GET 304 https://registry.npmjs.org/inherits 406ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/lodash 411ms
23 http fetch GET 304 https://registry.npmjs.org/debug 459ms (from cache)
24 silly pacote range manifest for inherits@^2.0.1 fetched in 439ms
25 silly resolveWithNewModule inherits@2.0.3 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/bluebird 487ms (from cache)
27 silly pacote range manifest for lodash@^4.6 fetched in 490ms
28 silly resolveWithNewModule lodash@4.17.10 checking installable status
29 silly pacote range manifest for debug@^2.2.0 fetched in 535ms
30 silly resolveWithNewModule debug@2.6.9 checking installable status
31 silly pacote range manifest for bluebird@^3.3.4 fetched in 548ms
32 silly resolveWithNewModule bluebird@3.5.1 checking installable status
33 silly pacote range manifest for queue@^3.1.0 fetched in 511ms
34 silly resolveWithNewModule queue@3.1.0 checking installable status
35 info lifecycle harmonyhubjs-client@0.1.0~prepack: harmonyhubjs-client@0.1.0
36 info lifecycle harmonyhubjs-client@0.1.0~postpack: harmonyhubjs-client@0.1.0
37 silly pacote git manifest for harmonyhubjs-client@github:e7hz3r0/harmonyhubjs-client fetched in 2998ms
38 silly resolveWithNewModule harmonyhubjs-client@0.1.0 checking installable status
39 http fetch GET 304 https://registry.npmjs.org/ms 98ms (from cache)
40 silly pacote version manifest for ms@2.0.0 fetched in 106ms
41 silly resolveWithNewModule ms@2.0.0 checking installable status
42 http fetch GET 200 https://registry.npmjs.org/node-xmpp-stanza 156ms
43 http fetch GET 304 https://registry.npmjs.org/request 163ms (from cache)
44 http fetch GET 200 https://registry.npmjs.org/node-xmpp-client 191ms
45 http fetch GET 304 https://registry.npmjs.org/q 190ms (from cache)
46 silly pacote range manifest for request@^2.48.0 fetched in 205ms
47 silly resolveWithNewModule request@2.85.0 checking installable status
48 silly pacote version manifest for node-xmpp-stanza@1.1.0 fetched in 230ms
49 warn deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
50 silly resolveWithNewModule node-xmpp-stanza@1.1.0 checking installable status
51 silly pacote version manifest for node-xmpp-client@3.0.0 fetched in 249ms
52 silly resolveWithNewModule node-xmpp-client@3.0.0 checking installable status
53 silly pacote range manifest for q@^1.1.2 fetched in 246ms
54 silly resolveWithNewModule q@1.5.1 checking installable status
55 silly fetchPackageMetaData error for ltx@git+https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /home/homebridge/.npm/_cacache/tmp/git-clone-257a97d3
55 silly fetchPackageMetaData /home/homebridge/.npm/_cacache/tmp/git-clone-257a97d3/.git: Keine Berechtigung
56 timing stage:rollbackFailedOptional Completed in 3ms
57 timing stage:runTopLevelLifecycles Completed in 5878ms
58 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /home/homebridge/.npm/_cacache/tmp/git-clone-257a97d3
58 verbose stack /home/homebridge/.npm/_cacache/tmp/git-clone-257a97d3/.git: Keine Berechtigung
58 verbose stack
58 verbose stack     at ChildProcess.exithandler (child_process.js:272:12)
58 verbose stack     at emitTwo (events.js:125:13)
58 verbose stack     at ChildProcess.emit (events.js:213:7)
58 verbose stack     at maybeClose (internal/child_process.js:927:16)
58 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
59 verbose cwd /usr/local/lib/node_modules
60 verbose Linux 4.14.34-v7+
61 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-update-notifier" "install" "--unsafe-perm" "homebridge-harmonyhub@latest"
62 verbose node v8.8.1
63 verbose npm  v6.0.1
64 error code 1
65 error Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /home/homebridge/.npm/_cacache/tmp/git-clone-257a97d3
65 error /home/homebridge/.npm/_cacache/tmp/git-clone-257a97d3/.git: Keine Berechtigung
66 verbose exit [ 1, true ]

Vielen Dank für die Hilfe....

**Comment by DJay-X** [comment]
`sudo chown -R $USER /usr/local && npm install homebridge-harmonyhub -g`

Worked for me.
