### ISSUE TITLE
HarmonyHub Plugin crashes my Homebridge

### ISSUE THREAD

**Issue by Crocy1104** [KraigM/homebridge-harmonyhub#140]
After starting the Homebridge with the HarmonyHub plugin, the Homebridge runs for about an hour. Then the homebridge runs into an error and is terminated. The following error occurs: 

Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/local/lib/node_modules/homebridge-marteksharmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/usr/local/lib/node_modules/homebridge-marteksharmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/usr/local/lib/node_modules/homebridge-marteksharmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-marteksharmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/local/lib/node_modules/homebridge-marteksharmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/local/lib/node_modules/homebridge-marteksharmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/local/lib/node_modules/homebridge-marteksharmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

Is there a workaround for this error? I haven't found anything useful on the Internet yet.

**Comment by Apple-76** [comment]
Have you found a solution? Been having this exact issue for the past 2-3 weeks or so and like you, I can’t seem to find a solution anywhere

**Comment by ssztemberg** [comment]
version 0.3.0 works perfectly fine for me ( `npm install -g homebridge-harmonyhub@0.3.0-alpha.2` )

**Comment by Apple-76** [comment]
This unfortunately did not work for me. Everything works fine and then a few hours into it it will cause HomeBridge to crash with the above error

**Comment by oetelaar24** [comment]
I think I may have a solution for you guys, see my comment here: 
https://github.com/KraigM/homebridge-harmonyhub/issues/137#issuecomment-414474654
