### ISSUE TITLE
udp port 5224 not unbound

### ISSUE THREAD

**Issue by elseym** [KraigM/homebridge-harmonyhub#15]
there seems to be a problem given:
- `~/.homebridge/config.json` does not contain an `ip_address` for the harmony hub
- `homebridge` has been started, quit by interrupt and started again
then the following error appears:
```code
[Harmony Hub] Initializing HarmonyHub platform...
[Harmony Hub] Searching for Logitech Harmony remote hubs...
Loading 0 accessories...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at dgram.js:213:18
    at nextTickCallbackWith3Args (node.js:466:9)
    at process._tickCallback (node.js:372:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
```

i do not know yet whether this can be solved in KraigM/homebridge-harmonyhub or in swissmanu/harmonyhubjs-discover

**Comment by KraigM** [comment]
Released in 0.1.1
