### ISSUE TITLE
Running Harmony Hub Error

### ISSUE THREAD

**Issue by sdorilas** [KraigM/homebridge-harmonyhub#157]
Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/timers.js:76:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/timers.js:76:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by kakiser56** [comment]
I also am experiencing this issue on the latest version 0.3.0-al;pha2 supported by HOOB.
