### ISSUE TITLE
"errorhub XMPP authentication failure" ?

### ISSUE THREAD

**Issue by payote** [KraigM/homebridge-harmonyhub#19]
Ignore - issue was with the idiot typing this. :smile:

**Comment by KraigM** [comment]
Ok lol

**Comment by pponce** [comment]
I'm getting the same error.
I'm a bit more of an idiot. How did you go about resolving?

**Comment by agaelx** [comment]
Hi how did you resolve this, I also got this error.
 code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect', ....
...
errorhub XMPP authentication failure

**Comment by pponce** [comment]
This might be related to issue #61.
To solve all the issues I was having I actually had to uninstall this plugin and I utilize a different project call HABridge that exposes itself and the harmony hub activities to homebridge as hue lights on a hue hub. Others have had luck with just reverting to the older version of this plugin.

**Comment by mgoblue01** [comment]
Can you explain to me, a novice for sure, what you had to do to install HABridge and expose it to Homebridge?

**Comment by pponce** [comment]
I followed the instructions here to get it installed:
https://github.com/bwssytems/ha-bridge
It uses port 80 to run a web server.  You configure it via the web interface that it enables when working correctly.  Enter in the harmony hup IP address and it should find your harmony activities.
You then configure the philips hue plugin for homebridge:
https://github.com/thkl/homebridge-philipshue 
If configure correctly it should find your HA-BRidge and see it as a hue hub.

Honestly though. solomonj1963 commented in issue #61 that the older version of this harmony hub plugin is working just fine.  It is probably easier to just install this older version instead of doing the above.
https://github.com/KraigM/homebridge-harmonyhub/releases/tag/0.1.1

**Comment by ChrisChiera** [comment]
Installed the other day and has been crashing a few times a day and I see the error, "errorhub XMPP authentication failure". My other hubs such as for Insteon devices works perfectly. When it does work, works great, and would love to integrate harmony into my HomeKit home since the possibilities are endless but from reading comments throughout GitHub sounds like currently it's quite buggy. Still great that this plugin exists and hopefully Logitech will officially support HomeKit with newer versions soon.

**Comment by mecrip** [comment]
I've got the very same issue. Just after the message I get also this exeption, and the homebridge stop responding at any query:

`
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (XMPP authentication failure)
    at Client.emit (events.js:144:17)
    at Client._handleAuthState (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:298:10)
    at Client._handleStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:234:12)
    at Client.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:369:10)
    at StreamParser.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:77:13)
    at StreamParser.emit (events.js:169:7)
    at SaxLtx.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:77:13)
    at SaxLtx.emit (events.js:169:7)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:28:22)
    at SaxLtx.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)

`

hope that this helps resolving
