### ISSUE TITLE
Error after some time in operation

### ISSUE THREAD

**Issue by Kohlibrie** [KraigM/homebridge-harmonyhub#24]
Hello,

After a few succesful acitivty settings of activities i get this error.

```
[Living Room Harmony Hub] Finished setting activity to 14899592
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
```

**Comment by Linoair** [comment]
I have exactly the same error here... Any ideas?

**Comment by KraigM** [comment]
what version of homebridge-harmonyhub and what version is its harmonyhubjs-client dependency?

**Comment by macchrissli** [comment]
i have the same problem.

**Comment by KraigM** [comment]
Put it in full debug mode so you can get better logs
`DEBUG=* homebridge -D`

**Comment by rickvdl** [comment]
I have the same issue, my output:
```
[Woonkamer Harmony] Finished setting activity to 19303337
[Woonkamer Harmony] Reconnecting to Hub 192.168.2.18
[Woonkamer Harmony] Connecting to Logitech Harmony remote hub...
[Woonkamer Harmony] Connected to Logitech Harmony remote hub
[Woonkamer Harmony] Reconnecting to Hub 192.168.2.18
[Woonkamer Harmony] Connecting to Logitech Harmony remote hub...
errorhub { [Error: connect EHOSTUNREACH 192.168.2.18:5222]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.2.18',
  port: 5222 }
[Woonkamer Harmony] Queue activity to -1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read EHOSTUNREACH
    at exports._errnoException (util.js:837:11)
    at TCP.onread (net.js:544:26)
```

**Comment by KraigM** [comment]
ok so it looks like either your IP changed or the hub was somehow unreachable on your network

**Comment by rickvdl** [comment]
Thanks for the quick response!
I can verify that the ip is still the same, restarted homebridge in debug and it reconnected.

**Comment by KraigM** [comment]
Yeah but in that moment, those two devices could not talk to each other (likely the harmony hub not responding)

**Comment by rickvdl** [comment]
Since homebridge can reconnect after a restart, shouldn't it be possible to for the homebridge plugin to reconnect while still running?

**Comment by KraigM** [comment]
Thats what it was trying to do, but something finally gave up

**Comment by rickvdl** [comment]
Yes I see, but after a restart it works though.
I will look into it and let you know. 
Thanks

**Comment by KraigM** [comment]
When you restart homebridge, there is a long period between stop and start.  Not to mention it puts it in a rediscovery phase which waits until it comes back.  The proper way to fix is to restructure the plugin to properly listen for lost/found hubs.  I have started this but I have to find the time.  I will gladly accept help

**Comment by rickvdl** [comment]
Yeah something like that should work. I am not rely experienced with Node or Javascript but ill see what I can do.

**Comment by KraigM** [comment]
I have started the restructure in the branch `feature/Restructure` but its a pretty big task.  Someone else posed a quick fix in that when it goes into its reconnect phase:

```
[Woonkamer Harmony] Reconnecting to Hub 192.168.2.18
[Woonkamer Harmony] Connecting to Logitech Harmony remote hub...
[Woonkamer Harmony] Connected to Logitech Harmony remote hub
[Woonkamer Harmony] Reconnecting to Hub 192.168.2.18
```
before it starts the actual reconnect, go into a ping loop until it is found.  This may or may not solve the issue since it could be the hub "overheating" if you will.

**Comment by KraigM** [comment]
possibly just putting a long delay in there may be a quick fix for you

**Comment by rickvdl** [comment]
So I should put a delay before the actual reconnect?

**Comment by rickvdl** [comment]
So about here:
```
plat.log("Reconnecting to Hub " + hubIP);
					createClient(hubIP, function (err, newHub) {
						if (err) throw err;
						hub = newHub;
						cb();
						if (funcMaxTimeout) {
							funcMaxTimeout();
						}
					});
```
Index.js:232

**Comment by KraigM** [comment]
Also my next release of [HomeBridgeController](https://github.com/KraigM/HomeBridgeController) (v0.6.0) has an auto restart capability in the plugin (https://github.com/KraigM/HomeBridgeController/issues/31) so that will def work around the issue

**Comment by jer78** [comment]
Is the restructure branch workable at the moment? Since I get this error every day I'm willing to try your other branch to help test. Thanks for all your hard work on this!! I use this plugin regularly.

**Comment by KraigM** [comment]
Not yet, but it is close

**Comment by jer78** [comment]
Great! Looking forward to it! Let me know if you need any assistance with testing. I know a little JavaScript but probably not enough to help :(

**Comment by rickvdl** [comment]
Same here, would love to use a new (working) version.

**Comment by KraigM** [comment]
In the next version (0.2.0) has been put into alpha.  If you wish to try it out (keeping in mind that it is a prerelease) you can upgrade to the alpha version using:
`npm install -g homebridge-harmonyhub@0.2.0-alpha`
