### ISSUE TITLE
Error Message During Startup

### ISSUE THREAD

**Issue by realdannys** [KraigM/homebridge-harmonyhub#27]
Can't get Homebridge to start at the minute due to this error.

    undefined:1

    SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:90:13)
    at Client.emit (events.js:182:7)
    at Client._handleStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:90:13)
    at Connection.emit (events.js:182:7)

Might also add that in the Home app on iOS its been throwing out authentication errors since the last Harmony hub upgrade relating to Harmony activities.

**Comment by KraigM** [comment]
Not sure on that one.  What versions are you using (harmony firmware, homebridge-harmonyhub, homebridge, etc)?
