### ISSUE TITLE
Error Message - UDID Problem

### ISSUE THREAD

**Issue by Muc38** [KraigM/homebridge-harmonyhub#40]
From what I read it seems the UUID of an accessory is pulled from the name.
Any idea? Here's my config:

[2016-07-18 21:38:59] [Harmony Hub] Found activities: 
	Smart TV wiedergeben
	Anhören Wohnzimmer
	Fussball im Zweiten
	Wiedergabe PS4
	Heimkino
	PowerOff
[2016-07-18 21:38:59] [Harmony Hub] Unable to get current activity with error [Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0096AA089285' and subtype '21431470' as another Service in this Accessory.]
Unhandled rejection Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0096AA089285' and subtype '21431470' as another Service in this Accessory.
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:132:15)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:62:34)
    at ActivityAccessory._getActivityService (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/activity-accessory.js:158:28)
    at /usr/local/lib/node_modules/homebridge-harmonyhub/lib/activity-accessory.js:121:22
    at arrayEach (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/lodash/lodash.js:451:11)
    at Function.forEach (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/lodash/lodash.js:8634:14)
    at ActivityAccessory._updateActivities (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/activity-accessory.js:120:4)
    at ActivityAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/activity-accessory.js:68:9)
    at ActivityAccessory.tryCatcher (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:501:35)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise_array.js:143:14)

**Comment by KradKrad** [comment]
delete the cachedAccessories file and then rerun homebridge.  Set it up the way you like it and then do the following..

"I had this same issue where it would crash my homebridge every few hours.  I just went and made the cached accessories file located at /home/username/.homebridge/accessories/cachedAccessories to READ ONLY.

Once it was set to read only, I would get the occasional access denied in homebridge logging, but it no longer crashes and harmonyhub plugin still works.
