### ISSUE TITLE
Harmony hub won't load after updating

### ISSUE THREAD

**Issue by havknfrack** [KraigM/homebridge-harmonyhub#45]
I just updated my Harmony hub with some new activities. After refreshing Homebridge to try and get them to appear, I received this:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at dgram.js:214:18
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

What was previously there is there. What's new is not.

**Comment by RickStirling** [comment]
Getting the exact same thing here.

The was working fine, now I get this:

events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at dgram.js:214:18
    at nextTickCallbackWith3Args (node.js:466:9)
    at process._tickCallback (node.js:372:17)
    at Function.Module.runMain (module.js:433:11)
    at startup (node.js:141:18)
    at node.js:977:3

**Comment by jer78** [comment]
I believe this error is due to multiple homebridge instances running. Try rebooting

**Comment by RickStirling** [comment]
Yeah, that fixed it.

I think it could be that my pi autoruns the script, and then I was logged in via ssh

**Comment by KraigM** [comment]
Closing this issue as it seems to be resolved.  Please reopen/repost if not.

**Comment by livefeed** [comment]
ok i and getting it too even after reboots

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by VeniceNerd** [comment]
Same here. This issue just started up. What can I do?

**Comment by andyhawks** [comment]
bump - this issue should not be closed. How does one resolve this issue if it persists on reboot? If I uninstall harmony-api and try and restart it I get the same error, but the only thing bound to the port is node.js activated from script/install, so it's in use from itself! Visiting the URL (at port 8282, the harmony-api port, not 5224 the node port) from a browser does not produce anything, just spins.
