### ISSUE TITLE
Ignoring Harmony Platform setup because it is not configured

### ISSUE THREAD

**Issue by scottatah** [KraigM/homebridge-harmonyhub#49]
Hey Folks,

My apologies for what is probably an amateur question, but I'm lookin for a little help.  Just installed homekit on a Win10 PC and can pair it with my iPhone.  I then tried installing the harmonyhub plugin via
`_npm install -g homebridge-harmonyhub_`

which returned the below (presumably good).
```
_C:\Users\finge\AppData\Roaming\npm
`-- homebridge-harmonyhub@0.2.0-alpha
  `-- harmonyhubjs-client@1.1.8
    `-- ltx@2.2.0  (git+https://github.com/swissmanu/ltx.git#ce9c34cc19319de8e65cadc3e360e8e5c290746d)_
```

I updated my config.json to be:
```
_{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "HomeBridge HTTP Status Control",

	"platforms": [{
		"platform": "HarmonyHub",
		"name": "Scotty's Harmony Hub",
		"ip_address": "192.168.1.15"
	}]

```
}

But when starting homekit, "Ignoring Harmony Platform setup because it is not configured":

```
C:\Users\finge\AppData\Roaming\npm\node_modules\homebridge\bin>node homebridge
[9/15/2016, 9:23:01 PM] Loaded plugin: homebridge-harmonyhub
[9/15/2016, 9:23:01 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[9/15/2016, 9:23:01 PM] ---
[9/15/2016, 9:23:02 PM] Loaded plugin: homebridge-http
[9/15/2016, 9:23:02 PM] Registering accessory 'homebridge-http.Http'
[9/15/2016, 9:23:02 PM] ---
Load homebridge-harmonyhub.HarmonyHub
[9/15/2016, 9:23:02 PM] [homebridge-harmonyhub.HarmonyHub] Ignoring Harmony Platform setup because it is not configured
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[9/15/2016, 9:23:02 PM] Homebridge is running on port 51826.
```

Can anyone point me in the right direction? Is it something with the plugin install?  The json file?  I've tried messing with both to no success as of yet.

Thanks,
Scott

**Comment by kylegracey** [comment]
Running into the same issue. The only difference with mine is that I'm not specifying "ip_address" in config.json. I'm getting the exact same result though.

I've been searching around for some kind of documentation on it and haven't been able to find anything.

**Comment by jer78** [comment]
My guess is it's not reading your config.json file. I don't have experience installing on a Windows machine but on a Mac there's 2 places with the config.json file. The correct one installs under <username/.homebridge folder. I'd do a search to see what directories it installs in Windows and edit the other file if there is one.

**Comment by martinhalle** [comment]
Hello, same thing over here, but on a Ubuntu 14.04. The config.json is in the .homebridge directory under my profile. Everything else is working fine (plugin Wink, PhilipsHue, etc)

**Comment by scottatah** [comment]
I followed https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows for my install.  According to the steps we put our config.json file in the C:\Users\xxx\.homebridge (where xxx=user profile).  I can remove/rename this file and I get the same error, so I agree that you might be onto something.  

Unfortunately, I don't have any tests to confirm it's in the correct spot like martinhalle suggested he has.  This is the only thing I've got homebridge installed for in Windows, however, I do have .node-gyp folder at the same level (presumably for when I upgraded) and it worked fine.  I've tried copying my config.json to a couple various folders in hopes that it might make a difference but no luck..

**Comment by ykoehler** [comment]
The proper location is C:\Users\xxx\.homebridge, I am unclear if you used xxx.homebridge or really xxx\.homebridge.

Your config.json also seems to start with an underscore.  That doesn't look right.

_{

**Comment by prbreezy** [comment]
Hey !

I don't know if you fix your issue but I was facing the same issue and it's not an issue actually it's a mistake. 
You wrongly implement the block section of the harmony hub.

The best way to help you is to post your config.json so I or we can figure out what's need to be changed.

Cheers !

**Comment by tomasMiddleton** [comment]
Why would you say it's wrongly implemented @prbreezy ?

**Comment by prbreezy** [comment]
Okay try the fellowing:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "HomeBridge HTTP Status Control",

	"platforms": [{
		"platform": "HarmonyHub",
		"name": "Harmony Hub"
	}]
}

**Then try this one**

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "HomeBridge HTTP Status Control",

	"platforms": [{
		"platform": "HarmonyHub",
		"name": "Harmony Hub"
	}, {
		"accessory": "WeMo",
		"name": "Coffee Maker"
	}, {
		"platform": "Orvibo"
	}]
}

In the first one you test only the harmony plugin then the second have everything.
Not sure why you put Wemo separately you should follow thins sample : https://www.npmjs.com/package/homebridge-platform-wemo

Let me know.

**Comment by tomasMiddleton** [comment]
The WeMo was the one from the sample, just didn't deleted it.

The problem persists.  No change whatsoever. 
In fact, when loading just one of the platforms, it still loaded the rest of them, it seems that ot detects "homebridge-*" folders or something like that.

Maybe it's a configuration from the homebridge-harmonyhub side, but I don't want to mess it up if there's no need to change those files.

**Comment by prbreezy** [comment]
There is no configuration on harmony side even the first one doesn't work ? 
@tomasMiddleton

**Comment by tomasMiddleton** [comment]
No, it's the same error.

> Load homebridge-harmonyhub.HarmonyHub
[1/14/2017, 12:42:22 PM] [homebridge-harmonyhub.HarmonyHub] Ignoring Harmony Platform setup because it is not configured

**Comment by prbreezy** [comment]
run with **DEBUG=* homebridge**

**Comment by tomasMiddleton** [comment]
`tomasMiddleton:~ tomasmiddleton$ DEBUG=* /usr/local/lib/node_modules/homebridge/bin/homebridge
[1/14/2017, 12:54:15 PM] Loaded plugin: homebridge-harmonyhub
[1/14/2017, 12:54:16 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[1/14/2017, 12:54:16 PM] ---
[1/14/2017, 12:54:16 PM] Loaded plugin: homebridge-http
[1/14/2017, 12:54:16 PM] Registering accessory 'homebridge-http.Http'
[1/14/2017, 12:54:16 PM] ---
[1/14/2017, 12:54:16 PM] Loaded plugin: homebridge-platform-orvibo
[1/14/2017, 12:54:16 PM] Registering platform 'homebridge-platform-orvibo.Orvibo'
[1/14/2017, 12:54:16 PM] ---
[1/14/2017, 12:54:16 PM] config.json (/Users/tomasmiddleton/.homebridge/config.json) not found.
Load homebridge-harmonyhub.HarmonyHub
[1/14/2017, 12:54:16 PM] [homebridge-harmonyhub.HarmonyHub] Ignoring Harmony Platform setup because it is not configured
Load homebridge-platform-orvibo.Orvibo
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  Orvibo Preparing connection and listening +0ms
  EventedHTTPServer Server listening on port 58993 +0ms
[1/14/2017, 12:54:16 PM] Homebridge is running on port 58993.
  Orvibo Socket bound to port 10000 +10ms
  Orvibo Broadcast set to true +2ms
  Orvibo Socket bound to port 9999 +3ms
  Orvibo Broadcast set to true +0ms
  Orvibo Socket bound to port 48899 +1ms
  Orvibo Broadcast set to true +0ms
  EventedHTTPServer [::ffff:10.0.1.4] New connection from client +992ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP server listening on port 58994 +1ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP request: /pair-verify +11ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +5ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP Response is finished +15ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP request: /pair-verify +21ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Client E58A8CDC-071A-460C-8EC2-8E950BAA8E31 verification complete +2ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP request: /accessories +5ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP request: /characteristics +25ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":15,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.4] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.56] New connection from client +135ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP server listening on port 58997 +1ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP request: /pair-verify +36ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:30] Client E58A8CDC-071A-460C-8EC2-8E950BAA8E31 verification complete +1ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP request: /accessories +10ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP request: /characteristics +47ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":15,"ev":true}] +4ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.56] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.36] New connection from client +681ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP server listening on port 59001 +1ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP request: /pair-verify +30ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Client E58A8CDC-071A-460C-8EC2-8E950BAA8E31 verification complete +1ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP request: /accessories +5ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP request: /characteristics +24ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":15,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.36] HTTP Response is finished +0ms
  Orvibo Discovery packet sent +5s
  Orvibo Discovery packet sent +2ms
  Orvibo Discovery packet sent +0ms
  Orvibo Message sent to 255.255.255.255:10000 with length 6 +10ms
  Orvibo Message sent to 255.255.255.255:10000 with length 6 +0ms
  Orvibo Message sent to 255.255.255.255:10000 with length 6 +1ms
  Orvibo Message received 6864002a716100accf239cce6c2020202020206cce9c23cfac202020202020534f433030352dc824dc01 { address: '10.0.1.5', family: 'IPv4', port: 10000, size: 42 } +14ms
  Orvibo Parsing incoming message. Command ID is: 7161 +12ms
  Orvibo Found socket! +1ms`

**Comment by prbreezy** [comment]
We got something here :+1: 
**/Users/tomasmiddleton/.homebridge/config.json**

paste your config.json in this place and let me know.

**Comment by tomasMiddleton** [comment]
Loaded but got a Node problem now 

`[1/14/2017, 12:59:03 PM] Loaded plugin: homebridge-harmonyhub
[1/14/2017, 12:59:03 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[1/14/2017, 12:59:03 PM] ---
[1/14/2017, 12:59:04 PM] Loaded plugin: homebridge-http
[1/14/2017, 12:59:04 PM] Registering accessory 'homebridge-http.Http'
[1/14/2017, 12:59:04 PM] ---
[1/14/2017, 12:59:04 PM] Loaded plugin: homebridge-platform-orvibo
[1/14/2017, 12:59:04 PM] Registering platform 'homebridge-platform-orvibo.Orvibo'
[1/14/2017, 12:59:04 PM] ---
[1/14/2017, 12:59:04 PM] Loaded config.json with 0 accessories and 3 platforms.
[1/14/2017, 12:59:04 PM] ---
[1/14/2017, 12:59:04 PM] Loading 3 platforms...
[1/14/2017, 12:59:04 PM] [Harmony Hub] Initializing HarmonyHub platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:104
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:104:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

**Comment by prbreezy** [comment]
Which version are you using ?

**Comment by tomasMiddleton** [comment]
Node: 6.9.1

**Comment by prbreezy** [comment]
Sorry version of the plugin ?
https://www.npmjs.com/package/homebridge-harmonyhub . - 0.2 ?

**Comment by tomasMiddleton** [comment]
Yes, 0.2

**Comment by prbreezy** [comment]
I have it works on my macOSX I jsut moved to an windows 10 but on my mac I have this version
**node -v**
**v6.9.3**

And homebridge do a **npm list**
MacBook-Pro:~ prbreezy$ npm list
/Users/prbreezy
└─┬ homebridge@0.4.16
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.0.0
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├─┬ commander@2.8.1
  │ └── graceful-readlink@1.0.1
  ├─┬ hap-nodejs@0.4.20
  │ ├── buffer-shims@1.0.0
  │ ├─┬ curve25519-n@1.1.0
  │ │ ├── bindings@1.2.1
  │ │ └── nan@2.5.0
  │ ├─┬ debug@2.6.0
  │ │ └── ms@0.7.2
  │ ├── ed25519@0.0.4
  │ ├── fast-srp-hap@1.0.0
  │ ├── ip@1.1.4
  │ └─┬ mdns@2.3.3
  │   └── nan@2.3.5
  ├─┬ node-persist@0.0.8
  │ ├── mkdirp@0.3.5
  │ └── q@1.1.2
  └── semver@5.0.3

**Comment by tomasMiddleton** [comment]
tomasMiddleton:homebridge tomasmiddleton$ npm list
homebridge@0.4.16 /usr/local/lib/node_modules/homebridge
├─┬ chalk@1.1.3
│ ├── ansi-styles@2.2.1
│ ├── escape-string-regexp@1.0.5
│ ├─┬ has-ansi@2.0.0
│ │ └── ansi-regex@2.1.1
│ ├── strip-ansi@3.0.1
│ └── supports-color@2.0.0
├─┬ commander@2.8.1
│ └── graceful-readlink@1.0.1
├─┬ hap-nodejs@0.4.20
│ ├── buffer-shims@1.0.0
│ ├─┬ curve25519-n@1.1.0
│ │ ├── bindings@1.2.1
│ │ └── nan@2.5.0
│ ├─┬ debug@2.6.0
│ │ └── ms@0.7.2
│ ├── ed25519@0.0.4
│ ├── fast-srp-hap@1.0.0
│ ├── ip@1.1.4
│ └─┬ mdns@2.3.3
│   └── nan@2.3.5
├─┬ node-persist@0.0.8
│ ├── mkdirp@0.3.5
│ └── q@1.1.2
└── semver@5.0.3

**Comment by prbreezy** [comment]
We have the same version.

WhatI can suggest is to:
Check if any update is available by running this command : **npm -g outdated**

And redo the tutorial for MacOSX: https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-OSX

**Comment by tomasMiddleton** [comment]
As this poster (simonrb2000) says (https://github.com/nfarina/homebridge/issues/756, I deleted the accessory and now it ran and also recognized all my activities.

Thank you @prbreezy

**Comment by prbreezy** [comment]
Great !

Enjoy homebrige ! 
@tomasMiddleton 
_We can close this topic now._

**Comment by mactwin** [comment]
Hi running plugin on raspberry this is the error

Load homebridge-harmonyhub.HarmonyHub
[2018-11-24 07:40:55] [homebridge-harmonyhub.HarmonyHub] Ignoring Harmony Platform setup because it is not configured


In my config.json:

  "bridge" : {
    "username" : "DD:11:36D:D3:CE:36",
    "name" : "HOMEBRIDGE",
    "pin" : "111-11-111",
    "port" : 51826
  	     },
   "platforms": [
   	{
   		"platform": "HarmonyHub",
   		"name": "Harmony Hub" 
  	}
   ]
