### ISSUE TITLE
homebridge won't work after instaling this plug in

### ISSUE THREAD

**Issue by NikoTheBoss** [KraigM/homebridge-harmonyhub#53]
Hello, 
i just installed this plugin and after this my HomeBridge won't start any more.
any idea?

kind regards 
Niko 

[10/5/2016, 7:35:41 PM] [Wohnzimmer] Initializing HarmonyHub platform...
[10/5/2016, 7:35:42 PM] Loading 0 accessories...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by RXM307** [comment]
sounds like you have something else running on port 5224 from Error: bind EADDRINUSE 0.0.0.0:5224, try running netstat -an | grep 5224
this will confirm or perhaps you have two copies of homebridge running?

**Comment by ewgor** [comment]
Hi,
I have kinda same problem. I installed the plugin but I think my problem is related to the config.json file!
On the same config.json file I have successfully configured openhab platform and it's working well I guess but when I try to add another platform like Harmony the homebridge it's not starting because of the Logitech info added in the config.json file!
Does anyone have an example of config.json file configured with openhab and harmonyhub platforms?
Thanks for any advice.
