### ISSUE TITLE
Undefined error since updating

### ISSUE THREAD

**Issue by hypascend** [KraigM/homebridge-harmonyhub#56]
Hi,

I am getting the following error after updating, any ideas?

npm\node_modules\homebridge-harmonyhub\node_modules\harmonyhubjs-client\lib\login\hub.js:59
      if (response.identity && response.identity !== undefined) {
                  ^

TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\harmonyhubjs-client\lib\login\hub.js:59:19)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client._handleStanza (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\node-xmpp-client\lib\Client.js:227:12)
    at Client.onStanza (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\node-xmpp-client\lib\Client.js:221:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.onStanza (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\node-xmpp-core\lib\Connection.js:377:10)
    at StreamParser.<anonymous> (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\node-xmpp-core\lib\Connection.js:231:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\@xmpp\streamparser\index.js:59:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\@xmpp\streamparser\node_modules\ltx\lib\parsers\ltx.js:36:12)
    at SaxLtx.write (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\@xmpp\streamparser\node_modules\ltx\lib\parsers\ltx.js:96:18)
    at StreamParser.write (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\@xmpp\streamparser\index.js:124:17)
    at Connection.onData (C:\Users\annih_000\AppData\Roaming\npm\node_modules\homebridge-harmonyhub\node_modules\node-xmpp-core\lib\Connection.js:310:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)

**Comment by andijegg** [comment]
The exact same error here, after clean install of my System yesterday.

**Comment by IceCreamGuys** [comment]
Ditto - Clean install, and this is all I get now.

**Comment by ekadosh** [comment]
Same here - totally fresh install.

**Comment by Iormangund** [comment]
Same error, clean install today.

**Comment by ekadosh** [comment]
I'm on Ubuntu 16.04.1

Error: 

```
/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/login/hub.js:59
      if (response.identity && response.identity !== undefined) {
                  ^

TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/login/hub.js:59:19)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at Client._handleStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:227:12)
    at Client.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:77:13)
    at StreamParser.emit (events.js:169:7)
    at SaxLtx.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/index.js:59:14)
    at emitOne (events.js:77:13)
    at SaxLtx.emit (events.js:169:7)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/node_modules/ltx/lib/parsers/ltx.js:36:12)
    at SaxLtx.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/node_modules/ltx/lib/parsers/ltx.js:96:18)

```

**Comment by andijegg** [comment]
Just For workaround until Fix.

Can someone explain how I can get back to Version 0.1.1?

Thanks

**Comment by andijegg** [comment]
Little workaround that works for me, so that I can use home bridge until fix

Fallback to Version 0.1.1

sudo npm uninstall -g homebridge-harmonyhub
then
sudo npm install -g homebridge-harmonyhub@0.1.1

With Version 0.1.1 my Homebridge starts without Problems config.json is the same as in Version 0.2.0 without a static ipaddress

**Comment by RXM307** [comment]
Theres been a few releases of homebridge also in the past few weeks, have
you tried upgrading this also?

**Comment by andijegg** [comment]
I did a clean install of the hole System yesterday including a fresh install of homebridge over npm

**Comment by Spbyte** [comment]
Same error here. I think it's related to a this [problem](https://github.com/swissmanu/harmonyhubjs-client/issues/20) in the harmonyhubjs-client library. It's an old error but seems to be the same issue.

**Comment by andijegg** [comment]
Which node version should be installed? I've running 4.6.0...

**Comment by Spybyte** [comment]
4.6.0 worked fine until yesterday. I also tried 5.12.0. No success so far...

**Comment by solognt** [comment]
Same here, I'm on ubuntu 16.04.1 and node 6.3.1

**Comment by jsg4** [comment]
Seeing this too.

**Comment by murch1** [comment]
Same error here.

**Comment by tomto147** [comment]
and same here. Had to downgrade to 0.1.1

**Comment by jabesq** [comment]
same here . Had to downgrade to 0.1.1

**Comment by bkonings** [comment]
I have the same issue, 0.1.1 works fine.

**Comment by tstraus13** [comment]
I have this same issues as well. Clean install on Ubuntu 16.04. Thanks.

**Comment by Spybyte** [comment]
swissmanu did a fix in his harmonyhubjs-client. I just installed the current version (0.2.0) of homebridge-harmonyhub. So far it seems to work again.

**Comment by andijegg** [comment]
Yes, here it is working too, since today.
