### ISSUE TITLE
Error when running home bridge

### ISSUE THREAD

**Issue by livefeed** [KraigM/homebridge-harmonyhub#58]
Hello, I am receiving the following error when i run home bridge, any ideas?

TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/login/hub.js:59:19)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client._handleStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:227:12)
    at Client.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/index.js:59:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/node_modules/ltx/lib/parsers/ltx.js:36:12)
    at SaxLtx.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/node_modules/ltx/lib/parsers/ltx.js:96:18)
    at StreamParser.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/index.js:124:17)
    at Connection.onData (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by JonSilver** [comment]
I'm getting this as well... please could you possibly tell me how you resolved it?
