### ISSUE TITLE
Failure on startup

### ISSUE THREAD

**Issue by cmarchant** [KraigM/homebridge-harmonyhub#59]
When I startup homebridge with harmonyhub installed, I receive the following error:

/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/login/hub.js:59
      if (response.identity && response.identity !== undefined) {
                  ^

TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/login/hub.js:59:19)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at Client._handleStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:227:12)
    at Client.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:77:13)
    at StreamParser.emit (events.js:169:7)
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/index.js:59:14)
    at emitOne (events.js:77:13)
    at SaxLtx.emit (events.js:169:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/node_modules/ltx/lib/parsers/ltx.js:36:12)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/@xmpp/streamparser/node_modules/ltx/lib/parsers/ltx.js:96:18)

Help to resolve much appreciated.

**Comment by Burry** [comment]
Having the same issue here on macOS Sierra. Tried uninstalling/reinstalling homebridge and homebridge-harmonyhub to no success

**Comment by tmThEMaN** [comment]
Same problem for days. Fresh install on Lubuntu, I tried everything and it's frustrating.

Maybe it has to do with a change in the hub or something ? Can't find references to the same problem related to Identity.
_"Cannot read property 'identity' of undefined"_

**Comment by Burry** [comment]
Looks like this is a pretty common issue. These guys figured out a temporary fix: downgrade homebridge-harmonyhub to an older build.

https://github.com/KraigM/homebridge-harmonyhub/issues/56

**Comment by cmarchant** [comment]
Thanks, after downgrading homebridge is running fine.

**Comment by ExPHAT** [comment]
Same for me, downgrading to 0.1.1 has fixed the issue.

**Comment by peporiz0r** [comment]
thanks, same here. downgrade helped. node 4.6 on raspberry 3
