### ISSUE TITLE
Unhandled rejection Error: EACCES: permission denied

### ISSUE THREAD

**Issue by thoduh** [KraigM/homebridge-harmonyhub#62]
Bekomme leider immer wieder folgende Fehler:

[2016-10-28 19:15:32] [Harmony Hub] Found activities: 
	Amazon
	PowerOff
	Apple TV
	Mac mini
	LED Licht
	BluRay
	Fernsehen
Unhandled rejection Error: EACCES: permission denied, open '/Users/MacMini/.homebridge/accessories/cachedAccessories'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:457:12)
    at Object.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:275:14)
    at Server._updateCachedAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:501:20)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:435:8)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:33:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:188:7)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:155:8)
    at /usr/local/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:149:15
    at PassThroughHandlerContext.finallyHandler (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:567:18)

**Comment by thoduh** [comment]
Jetzt funktioniert es:

sudo chmod g+rwx /Users/MacMini/.homebridge/accessories/cachedAccessories

Kann geschlossen werden :-)
