### ISSUE TITLE
I updated my harmony hub today to software version 4.11.6 …

### ISSUE THREAD

**Issue by Makk1000** [KraigM/homebridge-harmonyhub#69]
**and now homebridge-harmonyhub fails to find it on my network. I have uninstalled the plugin and reinstalled. I updated npm to version 4.0.2 and node is 6.9.1. 
Nothing has worked, I ran the debug and it displayed the error below:**

[11/7/2016, 10:59:50 PM] Loaded plugin: homebridge-harmonyhub
[11/7/2016, 10:59:51 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[11/7/2016, 10:59:51 PM] ---
[11/7/2016, 10:59:51 PM] Loaded plugin: homebridge-nest
[11/7/2016, 10:59:51 PM] Registering platform 'homebridge-nest.Nest'
[11/7/2016, 10:59:51 PM] ---
[11/7/2016, 10:59:51 PM] Loaded plugin: homebridge-thinkingcleaner
[11/7/2016, 10:59:51 PM] Registering accessory 'homebridge-thinkingcleaner.Roomba'
[11/7/2016, 10:59:51 PM] ---
[11/7/2016, 10:59:51 PM] Loaded config.json with 2 accessories and 2 platforms.
[11/7/2016, 10:59:51 PM] ---
[11/7/2016, 10:59:51 PM] Loading 2 platforms...
[11/7/2016, 10:59:51 PM] Initializing Nest platform...
[11/7/2016, 10:59:51 PM] Fetching Nest devices.
[11/7/2016, 10:59:51 PM] [Living Room Hub] Initializing HarmonyHub platform...
  harmonyhubjs:discover:explorer Explorer(61991) +0ms
  harmonyhubjs:discover:ping Ping(61991) +1ms
  harmonyhubjs:discover:explorer start() +3ms
  harmonyhubjs:discover:responsecollector ResponseCollector(61991) +1ms
  harmonyhubjs:discover:responsecollector start() +1ms
  harmonyhubjs:discover:ping start() +5ms
[11/7/2016, 10:59:51 PM] Loading 2 accessories...
[11/7/2016, 10:59:51 PM] [LivingRoomba] Initializing Roomba accessory...
  superagent max redirects 5 +0ms
  superagent GET http://10.0.1.18/full_status.json +10ms
  superagent timeout 60000ms GET http://xxx.xxx.x.xx/full_status.json +1ms
[11/7/2016, 10:59:51 PM] [BedRoomba] Initializing Roomba accessory...
  superagent max redirects 5 +9ms
  superagent GET http://xxx.xxx.x.xx/full_status.json +3ms
  superagent timeout 60000ms GET http://10.0.1.19/full_status.json +0ms
[11/7/2016, 10:59:51 PM] [Living Room Hub] Finalizing Plugin Launch
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::61991
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at ResponseCollector.start (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-discover/lib/responseCollector.js:33:5)
    at Explorer.start (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-discover/lib/explorer.js:75:25)
    at new HomePlatform (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:66:17)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:291:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Any ideas on a fix?

regards

Makk**

**Comment by solomonj1963** [comment]
I also use HA-Bridge and see they found solution just a few minutes ago.  Reference [here](https://github.com/bwssytems/ha-bridge/pull/248).  Hope that helps!  Maybe the same changes can be worked into homebridge-harmonyhub.

**Comment by radiocolin** [comment]
Homebridge is also failing to see any of my Harmony activities running bridge software 4.11.6.
