### ISSUE TITLE
Error after a while ETIMEDOUT / EHOSTUNREACH

### ISSUE THREAD

**Issue by joq3** [KraigM/homebridge-harmonyhub#70]
Hi,

Just installed this plugin, and as you can see it works and finds my Harmony Hub just fine. But if I leave the terminal window open and check back later on, I get the error down below.

What is this error? And what can I do about it?

Thank you!

`
[2016-11-08 14:28:53] Homebridge is running on port 51827.
[2016-11-08 14:28:54] [Harmony Hub] Fetching Logitech Harmony activities...
[2016-11-08 14:28:55] [Harmony Hub] Found activities:
        PowerOff
        Music
        TV
        PC
        Steam
        Kitchen
        Xbox
        Chromecast
errorhub { Error: connect ETIMEDOUT 192.168.1.12:5222
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.12',
  port: 5222 }
errorhub { Error: connect EHOSTUNREACH 192.168.1.12:5222
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.12',
  port: 5222 }

`

**Comment by joq3** [comment]
Also, when I let it run for a while and check the logs with this command:
tail -f /var/log/homebridge.err
I get this error:

>     at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)


I guess that's the MAX_CLIENTS error?

Is there a new version that solves both these problems?

I've tried power cycle the hub, works a bit longer, but crashes all the time. I got 1 Hub and 6 Activities.

**Comment by joq3** [comment]
0.2.0 version doesn't work good at all, I had to go back to an older version of this plugin.
But even the older version has problems. If I do any change to Harmony Hub and the hub reloads it starts crashing often. If I power cycle it, it will work for a few days.

This is the error:

> events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)

So, if I use 0.2.0 I get MAX_CLIENTS. If I use the older version it works better but I get ECONNRESET.

When is an update coming?

**Comment by sommo** [comment]
with 0.2.0 i also get:
ETIMEDOUT

**Comment by agaelx** [comment]
I also get this kind of error, do you have an idea where to apply a fix? thanks

errorhub { Error: connect ETIMEDOUT 10.0.1.25:5222
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.0.1.25',
  port: 5222 }
errorhub { Error: connect ETIMEDOUT 10.0.1.25:5222
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.0.1.25',
  port: 5222 }

**Comment by valshare** [comment]
Homebridge crashs, if harmony is shortly (for power saving as example) not avaible in network.

hope there will be a fix soon for this issue and static ip_address config in config.json.

```
[2017-01-17 22:06:25] [Living Room Harmony Hub] Reconnecting to Hub 10.255.251.1
[2017-01-17 22:06:25] [Living Room Harmony Hub] Connecting to Logitech Harmony r
errorhub { [Error: connect EHOSTUNREACH 10.255.251.14:5222]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.255.251.14',
  port: 5222 }
events.js:141
      throw er; // Unhandled 'error' event

```

**Comment by r32er** [comment]
@valshare
I got the same error:

http://www.bilder-upload.eu/show.php?file=1956d3-1485362788.png

You speak about power saving from the hub? Could this saving be deactivated maybe?

My ip of the hub is static. Which version do you use? I got the max clients error with the 0.2. 

0.1 works better but still not stable. Because of the often reconnect from the network..
