### ISSUE TITLE
Homebridge crashes

### ISSUE THREAD

**Issue by TheRoolBool** [KraigM/homebridge-harmonyhub#74]
Hello, since some time the homebridge by the Harmony plugin after a few hours always aborted. In the log (/var/log/homebridge.err) is:

`Error: MAX_CLIENTS=6
at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)`

**Comment by fboulegue** [comment]
same here ...

**Comment by gibbo520** [comment]
idem for me !

**Comment by fboulegue** [comment]
I think the repo creator doesn't really care I also did try to reach out at slack but no replay

**Comment by sommo** [comment]
the same here:
[12/1/2016, 11:06:33 AM] Homebridge is running on port 51826.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by sommo** [comment]
the crash happened after 10hours of running

**Comment by sommo** [comment]
can't resolve for the crash, but by adding homebridge like a service, i resolve to autorerun the process in automatic, and it's ok, if it crash it get relaunch

**Comment by sommo** [comment]
follow this to get homebridge like a service:
https://timleland.com/setup-homebridge-to-start-on-bootup/

**Comment by TS-Tec** [comment]
Same here... Homebridge crashes and is terminated after serveral hours of running with this module!

**Comment by lyxalig** [comment]
debug log from DEBUG=* homebridge
` +1s
  harmonyhubjs:discover:responsecollector handle new connection +460ms
  harmonyhubjs:discover:responsecollector received data chunk +2ms
  harmonyhubjs:discover:responsecollector connection closed. emitting data. +2ms
  harmonyhubjs:discover:ping emit() +550ms
  harmonyhubjs:discover:responsecollector handle new connection +310ms
  harmonyhubjs:discover:responsecollector received data chunk +4ms
  harmonyhubjs:discover:responsecollector connection closed. emitting data. +1ms
  wemo-client Incoming Request for uuid:Insight-1_0-221449K1200E88: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<InsightParams>1|1481360062|8736|12335|107424|1209600|11|10995|1546384|19332688|2210</InsightParams>
</e:property>
</e:propertyset>

  xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">Z3Vlc3RAeC5jb20AZ3Vlc3QAZ3Vlc3Q=</auth> +0ms
  xmpp:connection receive: <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/> +10ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="x.com"> +0ms
  xmpp:connection receive: <stream:stream from='x.com' id='02843ce1' version='1.0' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'><stream:features><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:nx:xmpp-session'/></stream:features> +14ms
  xmpp:connection send: <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>gatorade</resource></bind> +0ms
  xmpp:connection receive: <iq id='bind' type='result'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><jid>1111/gatorade</jid></bind></iq> +11ms
  harmonyhubjs:client:login:hub XMPP client connected +0ms
  xmpp:connection send: <iq type="get" id="583724" from="guest"><oa xmlns="connect.logitech.com" mime="vnd.logitech.connect/vnd.logitech.pair">method=pair:name=harmonyjs#iOS6.0.1#iPhone</oa></iq> +1ms
  xmpp:connection receive: <iq/> +12ms
  harmonyhubjs:client:login:hub received XMPP stanza: <iq xmlns:stream="http://etherx.jabber.org/streams"/> +0ms
  xmpp:connection receive: <iq id="583724" to="guest" type="get"><oa xmlns='connect.logitech.com' mime='vnd.logitech.connect/vnd.logitech.pair' errorcode='200' errorstring='OK'><![CDATA[serverIdentity=aad1bf19-9a96-46ef-9813-fcaa9be8fcc7:hubId=106:identity=aad1bf19-9a96-46ef-9813-fcaa9be8fcc7:status=succeeded:protocolVersion={XMPP="1.0", HTTP="1.0", RF="1.0", WEBSOCKET="1.0"}:hubProfiles={Harmony="2.0"}:productId=Pimento:friendlyName=Harmony Hub]]></oa></iq> +183ms
  harmonyhubjs:client:login:hub received XMPP stanza: <iq id="583724" to="guest" type="get" xmlns:stream="http://etherx.jabber.org/streams"><oa xmlns="connect.logitech.com" mime="vnd.logitech.connect/vnd.logitech.pair" errorcode="200" errorstring="OK">serverIdentity=aad1bf19-9a96-46ef-9813-fcaa9be8fcc7:hubId=106:identity=aad1bf19-9a96-46ef-9813-fcaa9be8fcc7:status=succeeded:protocolVersion={XMPP="1.0", HTTP="1.0", RF="1.0", WEBSOCKET="1.0"}:hubProfiles={Harmony="2.0"}:productId=Pimento:friendlyName=Harmony Hub</oa></iq> +1ms
  harmonyhubjs:client:login:hub received identity token: aad1bf19-9a96-46ef-9813-fcaa9be8fcc7 +0ms
  xmpp:connection send: </stream:stream> +0ms
  harmonyhubjs:client:login:hub create xmpp client using retrieved identity token: aad1bf19-9a96-46ef-9813-fcaa9be8fcc7 +0ms
  xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +0ms
  xmpp:connection use lazy socket +0ms
  xmpp:connection setup stream +0ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="connect.logitech.com"> +26ms
  xmpp:connection receive: <?xml version='1.0' encoding='iso-8859-1'?><stream:stream from='HarmonyOne_Pop@qa1.com' to='ab903454-7bee-4410-9eea-bb5355bb667e' version='1.0' id='connection-failure' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'><stream:error><resource-constraint xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams' xml:lang='en'>MAX_CLIENTS=6</text></stream:error></stream:stream> +11ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
`

**Comment by lyxalig** [comment]
#31

**Comment by rudibarani** [comment]
Same for me. Crashes after 3-4 hours...

**Comment by dom-it** [comment]
same here... agree with fboulegue ... :-/

**Comment by dom-it** [comment]
Being annoyed with the ongoing crashes ("Error: MAX_CLIENTS=6...") with version 0.2 and the developer not really caring to fix this, I downgraded to version 0.1.1, and it's working flawlessly since then ... not even had to change the config, the hub and all activities were there imediately.

**Comment by TheRoolBool** [comment]
Is there anything from the developer? Or has the project died?

**Comment by phrz** [comment]
It seems a dead project.

**Comment by sommo** [comment]
hope not, anyway, when i forced homebridge to run as a service, when it crash it get automatically relaunch

**Comment by TheRoolBool** [comment]
The developer unfortunately does not speak. @sommo How did you do it, so that it starts with a crash again automatically?

**Comment by sommo** [comment]
yes, it run homebridge as a service, so it continous check if the daemon is running and if not it launch it (for example if harmony plugin crash the homebridge). if u watch upper u will see my comment on how to make it, i wrote that:
follow this to get homebridge running like a service:
https://timleland.com/setup-homebridge-to-start-on-bootup/

u can also checking it's uptime/status once installed, by this command:
sudo systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Mon 2017-01-23 20:19:07 UTC; 1 day 7h ago
 Main PID: 1859 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─1859 homebridge

as u see it was relaunch 1day and 7h ago, i get bigger uptime anyway without that it's a pain in the ass

**Comment by sommo** [comment]
ofcourse u can stop, restart, start... if u need to make change on config.json (like i do, if i have to add/edit device on config.json i prefer to stop it), u can also active a debug... basically i think it's a must have, let me know, bye
