### ISSUE TITLE
Error: bind EADDRINUSE 0.0.0.0:5224

### ISSUE THREAD

**Issue by VeniceNerd** [KraigM/homebridge-harmonyhub#83]
Hi,

I had the Harmonyhub running perfectly for a while but all of a sudden I can no longer start Homebridge. I get the following error message:

```
Philipp-iMac-Home:~ Philipp$ homebridge
[1/22/2017, 3:33:40 PM] Loaded plugin: homebridge-harmonyhub
[1/22/2017, 3:33:40 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[1/22/2017, 3:33:40 PM] ---
[1/22/2017, 3:33:40 PM] Loaded plugin: homebridge-isy-js
[1/22/2017, 3:33:40 PM] Registering platform 'homebridge-isy-js.isy-js'
[1/22/2017, 3:33:40 PM] ---
[1/22/2017, 3:33:40 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/22/2017, 3:33:40 PM] ---
[1/22/2017, 3:33:40 PM] Loading 1 platforms...
[1/22/2017, 3:33:40 PM] [Harmony Hub] Initializing HarmonyHub platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 032-45-156 │     
    └────────────┘     
                       
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Here is a look at my config.json:

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:40",
		"port": 50920,
		"pin": "032-45-156"
	},

	"platforms": [{
		"platform": "HarmonyHub",
		"name": "Harmony Hub"
	}]
	}
```

Any idea how to troubleshoot this? I tried uninstalling the plugin and home bridge itself but it didn't help. :(

Thanks,

Philipp

**Comment by en2te** [comment]
Hi,
i get the same message on Raspberry Pi. It was running for a while but now i get the error on startup. Rebooting the pi don't help. Andy idea? 
Thank you in advance,
Tobias

**Comment by rfiorentino1** [comment]
same problem here. Anyone figured this out yet? Very annoying

**Comment by mgoblue01** [comment]
http://stackoverflow.com/questions/8553957/how-to-release-localhost-from-error-listen-eaddrinuse

This may help.  In the message above it looks like port 5224 is otherwise in use.

**Comment by rfiorentino1** [comment]
Thanks for this. I looked into this further, and tried a few things listed at that post, but nothing really gave me a concrete answer, at least one that I understood. I'm not much of a programmer ;) However, wouldn't it be easier to just change the port that the HarmonyHub plug-in is using? Does anyone know how to do that/where to look for the parameter?

**Comment by rfiorentino1** [comment]
Anyone have any luck resolving this? With help, I did figure out how to change the port for discovery of harmony...it's inside of your home bridge harmony hub folder of your global NPM location, in a file called home-platform.js
You can edit the line that says new discovery (61991). That solved my original "listen eaddrinuse 61991" error, but now I'm left with this one listed in this issue, about binding. I already reinstalled with no luck. Where did this come from? Did someone update the plugin? As stated above by other users, the plug-in was working fine for a while for me, and then this happened. Any solutions let us know :) thanks so much, just thought I'd post an update with what I've tried here in case it might help someone.

**Comment by RXM307** [comment]
check that another service is running on that port

netstat -an | grep 61991

**Comment by ruudux** [comment]
I also discover this issue.I am using Homebridge running on a raspberry pi and added the platforms for the homewizard and the harmoni hub. I also added the accessorie Nefit Easy. Everything worked fine, untill I added a second Harmoni hub. When running "homebridge status" or "homebridge restart" i'll get this output after the initializing notifications.
```
events.js:160                                                                throw er; // Unhandled 'error' event                                           ^                                                        Error: bind EADDRINUSE 0.0.0.0:5224                     
    at Object.exports._errnoException (util.js:1020:11)                    at exports._exceptionWithHostPort (util.js:1043:20)                
    at _handle.lookup (dgram.js:219:18)                                    at _combinedTickCallback (internal/process/next_tick.js:83:11)     
    at process._tickCallback (internal/process/next_tick.js:104:9)         at Module.runMain (module.js:606:11)                                   at run (bootstrap_node.js:383:7)                                   	    at startup (bootstrap_node.js:149:9)                            at bootstrap_node.js:496:3                                        ```          
When I run "netstat -tulpn | grep 5224" to check what is running on this port i'll get this output:
```
udp        0      0 0.0.0.0:52245224            0.0.0.0:*                           314/homebridge
```
Killing the proces and starting homebridge will get the same error.
Anybody found a working solution?

**Comment by myusuf3** [comment]
kicking the can, here again, looks like config doesn't change starting port for some reason
or does that port specifically need to be open for home kit connection?
