### ISSUE TITLE
Unhandled UUID issue

### ISSUE THREAD

**Issue by reallybman** [KraigM/homebridge-harmonyhub#86]
All - see the following error with this plugin. I can fix homebridge by deleting this plugin. 

Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b660bda3-dc65-4a52-92da-bbcede858240
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:189:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:155:8)
    at /usr/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:149:15
    at PassThroughHandlerContext.finallyHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:431:57)

**Comment by andyrooo82** [comment]
I had this issue. I deleted the accessories directory (which then gets recreated automatically) and then started working for me.

**Comment by reallybman** [comment]
@andyrooo82 Yes - I've tried that - my issue is, however, that whenever homebridge or the Pi restarts, I get the same issue. What I've done now, is, make the "cachedAccessories" file read-only and that seems to have fixed the issue. Homebridge still generates an error but it does not keep it from loading.

**Comment by mezza** [comment]
@reallybman Thanks for the hack fix.
