### ISSUE TITLE
depricated npmjs components

### ISSUE THREAD

**Issue by aguaman15** [KraigM/homebridge-harmonyhub#92]
Hi,

When I install HarmonyHub I receive 2 errors:

npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>

npm WARN deprecated node-xmpp-jid@2.3.0: use @xmpp/jid package <https://www.npmjs.com/package/@xmpp/jid>

I've tried installing the components from the above web sites, but then I get errors from Homebridge. So... any suggestions?

Homebridge and the HarmonyHub plugin seem to work fine at first, but after a while (a day or two) the HarmonyHub plugin stops working or, worse, gets confused with other devices. I imagine it's because of the above errors, but it's just a guess. 

Any ideas?

**Comment by CooperCGN** [comment]
I don't know if it has anything to do with that (I get that error too while installing) but my homebridge throws every now and then an error related with XMPP authentication failure. I wonder if this plug in is still under further development though.

Error: Uncaught, unspecified "error" event. (XMPP authentication failure)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at Client.emit (events.js:166:17)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at Client._handleAuthState (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:298:10)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at Client._handleStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:234:12)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at Client.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:222:8)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at emitOne (events.js:96:13)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at Connection.emit (events.js:191:7)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:369:10)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at emitOne (events.js:96:13)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at StreamParser.emit (events.js:191:7)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at emitOne (events.js:96:13)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at SaxLtx.emit (events.js:191:7)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:28:22)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
Jun 12 04:21:31 raspberrypi homebridge[3511]: at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
Jun 12 04:21:31 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jun 12 04:21:31 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by RXM307** [comment]
Perhaps there was a hub update?

Mine are both running 4.12.36, which was released 21st Nov 2016
https://support.myharmony.com/en-us/release-notes

I'm seeing this also today

was working 6/12/2017, 6:25:05AM AEST

but has been failing since 6/12/2017, 08:16 AEST

errorhub XMPP authentication failure
errorhub XMPP authentication failure

Cheers,

Anthony

**Comment by CooperCGN** [comment]
My hub is running 4.12.36 too. I guess all we can hope for is a fix as my JavaScript skillls are horrible ;)
Until then I keep auto restarting homebridge or hope now that Apple has lifted HomeKit restrictions Logitech will make it HomeKit compatible with the release of iOS 11

**Comment by RXM307** [comment]
An today it is working again.

very Odd!
