### ISSUE TITLE
Install fails | Git command fails

### ISSUE THREAD

**Issue by ultramizer** [KraigM/homebridge-harmonyhub#97]
Hi

I have set up Homebridge successfully and it seems to be running without crashing. I installed homebridge-netatmo for a test, and that installed without a problem. Now if i try to install harmonyhub, it fails.
Here's how i install it: `sudo npm -g homebridge-harmonyhub`, i also tried `sudo npm i -g homebridge-harmonyhub` but both fail with the following error:

`
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /root/.npm/_cacache/tmp/git-clone-31c9b6e1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-31c9b6e1': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-15T06_49_44_123Z-debug.log
`

The mentioned log shows a total of 59 lines, here is the last few of it:

`
50 silly resolveWithNewModule q@1.5.0 checking installable status
51 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /root/.npm/_cacache/tmp/git-clone-31c9b6e1
51 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-31c9b6e1': Permission denied
51 verbose stack
51 verbose stack     at ChildProcess.exithandler (child_process.js:252:12)
51 verbose stack     at emitTwo (events.js:125:13)
51 verbose stack     at ChildProcess.emit (events.js:213:7)
51 verbose stack     at maybeClose (internal/child_process.js:887:16)
51 verbose stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
51 verbose stack     at emitOne (events.js:115:13)
51 verbose stack     at Socket.emit (events.js:210:7)
51 verbose stack     at Pipe._handle.close [as _onclose] (net.js:546:12)
52 verbose cwd /home/pi
53 verbose Linux 4.9.24+
54 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "homebridge-harmonyhub"
55 verbose node v8.0.0
56 verbose npm  v5.0.0
57 error code 128
58 error Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /root/.npm/_cacache/tmp/git-clone-31c9b6e1
58 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-31c9b6e1': Permission denied
59 verbose exit [ 1, true ]
`

Can someone help me with this?

**Comment by jdshkolnik** [comment]
I'm having the same issue when trying to install homebridge-nest. These repos don't seem to be maintained.

**Comment by sefki21** [comment]
facing the same issue... found any solution?

**Comment by ultramizer** [comment]
I actually managed to solve it by using Option 1 from this page:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

Find the path to npm's directory:
`npm config get prefix`
For many systems, this will be /usr/local.
**WARNING: If the displayed path is just /usr, switch to Option 2 or you will mess up your permissions.**
Change the owner of npm's directories to the name of the current user (your username!):
`sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`
This changes the permissions of the sub-folders used by npm and some other tools (lib/node_modules, bin, and share).

After that, install the plugin without `sudo` so just do: `npm -g homebridge-harmonyhub` and that should work! Let me know, so i will close this issue.

**Comment by sefki21** [comment]
had to use option 2 (default directory: /usr) - but did it! thank you!

**Comment by sdorilas** [comment]
I've tried both options and I still cannot install Homebridge-arlo. After doing option 1 -- PMS wouldn't open on my mac, I had to reinstall it.

**Comment by sdorilas** [comment]
Having same exact issue and I just now completed option 1. It appears all the permissions are correct but I still cannot get it to install:
home:~ sdorilas$ sudo chown -R sdorilas /usr/local/share/
home:~ sdorilas$ ls -la usr/local/share/
ls: usr/local/share/: No such file or directory
home:~ sdorilas$ ls -la /usr/local/share/
total 0
drwxrwxr-x   6 sdorilas  admin  204 May 31  2016 .
drwxr-xr-x  19 sdorilas  wheel  646 Feb 23 01:57 ..
drwxrwxr-x   4 sdorilas  admin  136 May 31  2016 doc
drwxrwxr-x   6 sdorilas  admin  204 Aug  8 15:28 man
drwxrwxr-x   3 sdorilas  wheel  102 May 24  2016 systemtap
drwxr-xr-x   3 sdorilas  admin  102 May 31  2016 zsh
home:~ sdorilas$ ls -la /usr/local/bin/
total 46144
drwxrwxr-x  10 sdorilas  admin       340 Aug 13 19:42 .
drwxr-xr-x  19 sdorilas  wheel       646 Feb 23 01:57 ..
-rw-r--r--@  1 sdorilas  admin      6148 Jul 31  2016 .DS_Store
-rwxr-xr-x   1 sdorilas  admin       656 May 31  2016 brew
-rw-r--r--@  1 sdorilas  wheel       284 May 30  2016 config.json
lrwxr-xr-x   1 sdorilas  admin        45 Aug 13 19:42 homebridge -> ../lib/node_modules/homebridge/bin/homebridge
-rwxrwxr-x   1 sdorilas  wheel  23590208 Jun 28  2016 node
lrwxr-xr-x   1 sdorilas  admin        38 Aug  8 15:28 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x   1 sdorilas  admin        38 Aug  8 15:28 npx -> ../lib/node_modules/npm/bin/npx-cli.js
lrwxr-xr-x   1 sdorilas  admin        34 May 31  2016 xbox-on -> ../lib/node_modules/xbox-on/cli.js
home:~ sdorilas$ sudo npm -g install homebridge-harmonyhub
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /Users/sdorilas/.npm/_cacache/tmp/git-clone-25cb82fa
npm ERR! /Users/sdorilas/.npm/_cacache/tmp/git-clone-25cb82fa/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sdorilas/.npm/_logs/2017-08-14T18_02_40_720Z-debug.log

**Comment by prbreezy** [comment]
Hello,

I'm having the same issue I try solution 1 and 2 and still the same issue :( 

Thanks for helping !

**Comment by prbreezy** [comment]
Hi
Any update on this recurring issue? I can provide any if needed.

**Comment by sdorilas** [comment]
No update at all. I will take any help at this time

**Comment by prbreezy** [comment]
Ok, I remove the plugin from my config.json for the past few days it's keeps crashing every hours.

**Comment by sdorilas** [comment]
Anyone have an update on this issue?

**Comment by swapy** [comment]
I was able to solve it temporarily by downgrading npm version.
`npm install -g npm@4`

**Comment by sdorilas** [comment]
That worked!! But now my MyQ platform doesn’t work.   Did you update the npm after?

**Comment by andrewgribben** [comment]
'npm install --unsafe-perm --verbose -g homebridge-harmonyhub'

Worked for me

**Comment by sujayjaju** [comment]
Thanks @andrewgribben 
Your comment made me realize that the issue was because I was running the command as root!
Running as a regular user fixed it for me.

**Comment by IlyasDeckers** [comment]
@ultramizer Watch out with this command. You will change owner on `/usr/bin/sudo` and this is something you really do not want!
```sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}```

To revert the changes on `/usr/bin/sudo`
```
# Log out as the current user, then log back in as root.
chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo
#Log out as root, then log back in as the current user.
```

**Comment by tyleransom** [comment]
@IlyasDeckers @ultramizer This happened to me today! I was able to get it fixed thanks to [this thread](https://askubuntu.com/questions/675296/changing-ownership-operation-not-permitted-even-as-root)

**Comment by ronytomen** [comment]
Down grading `npm` as per @swapy recommendation allowed me to install it as `root`.

**Comment by rolfen** [comment]
How can root have permission denied? The permissions look OK to me!

**Comment by sujayjaju** [comment]
Running as root allows potentially harmful installs to corrupt the system. Its a preventive measure to force explicit action (using ```--unsafe-perm```) to run as root.

**Comment by tatianajiselle** [comment]
I followed @ultramizer suggestion and on my linux distro i removed sudo access from root, essentially destroying my access privilege barrier for security. 

Im not sure if anyone else experienced this issue, but its certainly not a heatlhy work around...
`tatianajiselle@mars:~$ sudo
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set`

thankfully i am my only user, and having root access is alright, but i mean... not okay even still.

**Comment by RyanFromQA** [comment]
FYI the workaround that worked for me (Raspberry Pi Zero W running Stretch) was in that [last linked issue above](https://github.com/zwaldowski/homebridge-satellite-fan/issues/8#issuecomment-397781712):

```
pi@raspberrypi ~$ sudo su
root@raspberrypi:/home/pi# sudo npm install -g --unsafe-perm homebridge-harmonyhub
```

**Comment by sunilmbhoi** [comment]
> @ultramizer Watch out with this command. You will change owner on `/usr/bin/sudo` and this is something you really do not want!
> `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`
> 
> To revert the changes on `/usr/bin/sudo`
> 
> ```
> # Log out as the current user, then log back in as root.
> chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo
> #Log out as root, then log back in as the current user.
> ```

changing permission using command "sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}" is creating other issues with sudo binary and it is asking to set setuid bit.

**Comment by MajidJafari** [comment]
> I actually managed to solve it by using Option 1 from this page:
> https://docs.npmjs.com/getting-started/fixing-npm-permissions
> 
> Find the path to npm's directory:
> `npm config get prefix`
> For many systems, this will be /usr/local.
> **WARNING: If the displayed path is just /usr, switch to Option 2 or you will mess up your permissions.**
> Change the owner of npm's directories to the name of the current user (your username!):
> `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`
> This changes the permissions of the sub-folders used by npm and some other tools (lib/node_modules, bin, and share).
> 
> After that, install the plugin without `sudo` so just do: `npm -g homebridge-harmonyhub` and that should work! Let me know if that works for you, so i will close this issue.

If you are not sure what you are doing, don't do this. Using this on Manjaro caused me and some other people a real headache and recover from the situation was very tiresome.
