### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by sdorilas** [KraigM/homebridge-harmonyhub#99]
$ sudo npm install -g homebridge-harmonyhub
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! exited with error code: 69

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sdorilas/.npm/_logs/2017-08-02T19_34_41_920Z-debug.log

**Comment by sdorilas** [comment]
sudo npm install -g homebridge-harmonyhub
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/swissmanu/ltx.git
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 69

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sdorilas/.npm/_logs/2017-08-08T19_29_52_983Z-debug.log

**Comment by patrickbusch** [comment]
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


When you install it for the first time, you have to run `git` on the console once as root to accept the Xcode/iOS license agreement

**Comment by sdorilas** [comment]
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /Users/sdorilas/.npm/_cacache/tmp/git-clone-d0e73c34
npm ERR! /Users/sdorilas/.npm/_cacache/tmp/git-clone-d0e73c34/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sdorilas/.npm/_logs/2017-08-09T10_29_06_330Z-debug.log

**Comment by sdorilas** [comment]
sudo npm install -g homebridge-harmonyhub
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /Users/sdorilas/.npm/_cacache/tmp/git-clone-c892cacb
npm ERR! /Users/sdorilas/.npm/_cacache/tmp/git-clone-c892cacb/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sdorilas/.npm/_logs/2017-08-09T22_50_41_117Z-debug.log

**Comment by sdorilas** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-harmonyhub' ]
2 info using npm@5.3.0
3 info using node@v4.4.7
4 verbose npm-session c97bc8d0726b8115
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-harmonyhub 856ms (from cache)
8 silly pacote tag manifest for homebridge-harmonyhub@latest fetched in 966ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-harmonyhub@0.2.0 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/debug 492ms (from cache)
15 http fetch GET 304 https://registry.npmjs.org/harmonyhubjs-discover 550ms (from cache)
16 http fetch GET 304 https://registry.npmjs.org/lodash 544ms (from cache)
17 http fetch GET 304 https://registry.npmjs.org/inherits 549ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/bluebird 572ms (from cache)
19 silly pacote range manifest for debug@^2.2.0 fetched in 607ms
20 silly resolveWithNewModule debug@2.6.8 checking installable status
21 silly pacote range manifest for harmonyhubjs-discover@^1.0.2 fetched in 612ms
22 silly resolveWithNewModule harmonyhubjs-discover@1.0.3 checking installable status
23 silly pacote range manifest for bluebird@^3.3.4 fetched in 632ms
24 silly resolveWithNewModule bluebird@3.5.0 checking installable status
25 silly pacote range manifest for lodash@^4.6 fetched in 611ms
26 silly resolveWithNewModule lodash@4.17.4 checking installable status
27 silly pacote range manifest for inherits@^2.0.1 fetched in 631ms
28 silly resolveWithNewModule inherits@2.0.3 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/harmonyhubjs-client 642ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/queue 637ms (from cache)
31 silly pacote range manifest for harmonyhubjs-client@^1.1.6 fetched in 662ms
32 silly resolveWithNewModule harmonyhubjs-client@1.1.10 checking installable status
33 silly pacote range manifest for queue@^3.1.0 fetched in 657ms
34 silly resolveWithNewModule queue@3.1.0 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/ms 207ms (from cache)
36 silly pacote version manifest for ms@2.0.0 fetched in 259ms
37 silly resolveWithNewModule ms@2.0.0 checking installable status
38 http fetch GET 200 https://registry.npmjs.org/request 520ms (from cache)
39 silly pacote range manifest for request@^2.48.0 fetched in 535ms
40 silly resolveWithNewModule request@2.81.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/node-xmpp-client 644ms (from cache)
42 silly pacote version manifest for node-xmpp-client@3.0.0 fetched in 688ms
43 silly resolveWithNewModule node-xmpp-client@3.0.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/node-xmpp-stanza 691ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/q 692ms (from cache)
46 silly pacote version manifest for node-xmpp-stanza@1.1.0 fetched in 738ms
47 warn deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
48 silly resolveWithNewModule node-xmpp-stanza@1.1.0 checking installable status
49 silly pacote range manifest for q@^1.1.2 fetched in 745ms
50 silly resolveWithNewModule q@1.5.0 checking installable status
51 silly fetchPackageMetaData error for ltx@git+https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /Users/sdorilas/.npm/_cacache/tmp/git-clone-c892cacb
51 silly fetchPackageMetaData /Users/sdorilas/.npm/_cacache/tmp/git-clone-c892cacb/.git: Permission denied
52 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /Users/sdorilas/.npm/_cacache/tmp/git-clone-c892cacb
52 verbose stack /Users/sdorilas/.npm/_cacache/tmp/git-clone-c892cacb/.git: Permission denied
52 verbose stack
52 verbose stack     at ChildProcess.exithandler (child_process.js:213:12)
52 verbose stack     at emitTwo (events.js:87:13)
52 verbose stack     at ChildProcess.emit (events.js:172:7)
52 verbose stack     at maybeClose (internal/child_process.js:827:16)
52 verbose stack     at Socket.<anonymous> (internal/child_process.js:319:11)
52 verbose stack     at emitOne (events.js:77:13)
52 verbose stack     at Socket.emit (events.js:169:7)
52 verbose stack     at Pipe._onclose (net.js:486:12)
53 verbose cwd /Users/sdorilas
54 verbose Darwin 16.6.0
55 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-harmonyhub"
56 verbose node v4.4.7
57 verbose npm  v5.3.0
58 error code 1
59 error Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /Users/sdorilas/.npm/_cacache/tmp/git-clone-c892cacb
59 error /Users/sdorilas/.npm/_cacache/tmp/git-clone-c892cacb/.git: Permission denied
60 verbose exit [ 1, true ]

**Comment by JonSilver** [comment]
Exactly the same here.

**Comment by sdorilas** [comment]
Anything new @JonSilver?

**Comment by iDevo** [comment]
I've the same issue since I've updated Node JS to 8.4.0. 
I couldn't find a solution but maybe this helps the contributors.

PS: Manny thanks anyway, this is a great plugin and was working like a charm before! 🎉

**Comment by sdorilas** [comment]
I've never been able to get it to work at all. I appreciate him creating the plugin -- just wish there was a little more support but I'm sure others will assist over time. Thanks for chiming in!

**Comment by efloyd** [comment]
Oh man, I just received my Harmony Hub and went to install it, and received the same error. Homebridge was the only reason I ordered the Hub. I hope someone will be able to get the plugin install-able soon. I don't think I want to try downgrading my Node JS.

**Comment by sdorilas** [comment]
hey @efloyd, 

I tried this from a different forum, then it installed.

either way, running sudo npm install -g --unsafe-perm homebridge will upgrade you to the most recent version

**Comment by efloyd** [comment]
Thanks for the tip @sdorilas. I just updated homebridge. When I attempted to install the harmony plugin, I received some warnings, but I'm not sure if it successfully installed. So I thought I'd update my config file, but when I run homebridge, it says the harmony plugin wasn't found or registered.

**Comment by sdorilas** [comment]
Hmm I’m not too sure. I receiving warnings too but they’re just that. I would try to install again. Pay attention to the messages/errors. Mine worked fine and picked up all my activities.

**Comment by efloyd** [comment]
Here's the error that I'm getting:

pi@raspberrypi:~ $ npm i -g homebridge-harmonyhub
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm WARN deprecated node-xmpp-jid@2.3.0: use @xmpp/jid package <https://www.npmjs.com/package/@xmpp/jid>
+ homebridge-harmonyhub@0.3.0-alpha.2
updated 1 package in 15.768s

**Comment by efloyd** [comment]
Success! I was able to solve my problem. I found some instructions online for logging in as root. When I did, I found that my root password was locked, so I reset the root password and logged in successfully as root. 

Then, I followed the instructions to install the homebridge-harmonyplugin, and it worked! Installed with no errors. Once I updated my config file, and started homebridge, homebridge found my activities and those activities then appeared in my Home app.

**Comment by sdorilas** [comment]
Yay!! Glad to hear it. Enjoy those activities on your Home app.
